apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: k8s-on-eks-pro
  region: us-east-1
nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
    privateNetworking: false
    